### ISSUE TITLE
Just Installed It

### ISSUE THREAD

**Issue by SiahRBLX** [Taylor-pm-pl/EpicCustomAlerts#1]
[16:32:51.824] [Server thread/CRITICAL]: TypeError: "str_replace(): Argument #2 ($replace) must be of type array|string, int given" (EXCEPTION) in "plugins/EpicCustomAlerts.phar/src/Loader" at line 70
--- Stack trace ---
  #0 plugins/EpicCustomAlerts.phar/src/Loader(70): str_replace(string[12] {MAXPLAYERS}, integer 20, string[65] &2[{TIME}] &aModdingTwinz&e moved from &c{ORIGIN}&e to &a{TARGET})
  #1 plugins/EpicCustomAlerts.phar/src/listener/EventListener(104): davidglitch04\EpicCustomAlerts\Loader->getMessage(string[11] WorldChange, array[6])
  #2 pmsrc/src/event/RegisteredListener(75): davidglitch04\EpicCustomAlerts\listener\EventListener->onChangeWorld(object pocketmine\event\entity\EntityTeleportEvent#100273)
  #3 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityTeleportEvent#100273)
  #4 pmsrc/src/entity/Entity(1423): pocketmine\event\Event->call()
  #5 pmsrc/src/player/Player(2373): pocketmine\entity\Entity->teleport(object pocketmine\world\Position#100289, NULL , NULL )
  #6 plugins/AlwaysSpawn.phar/src/philipshilling/alwaysspawn/Loader(15): pocketmine\player\Player->teleport(object pocketmine\world\Position#100289)
  #7 pmsrc/src/event/RegisteredListener(75): philipshilling\alwaysspawn\Loader->onPlayerLogin(object pocketmine\event\player\PlayerLoginEvent#100201)
  #8 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerLoginEvent#100201)
  #9 pmsrc/src/Server(1667): pocketmine\event\Event->call()
  #10 pmsrc/src/network/mcpe/NetworkSession(243): pocketmine\Server->addOnlinePlayer(object pocketmine\player\Player#100230)
  #11 pmsrc/src/promise/Promise(45): pocketmine\network\mcpe\NetworkSession->onPlayerCreated(object pocketmine\player\Player#100230)
  #12 pmsrc/src/network/mcpe/NetworkSession(234): pocketmine\promise\Promise->onCompletion(object Closure#100208, object Closure#100223)
  #13 pmsrc/src/network/mcpe/NetworkSession(692): pocketmine\network\mcpe\NetworkSession->createPlayer()
  #14 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(142): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #15 pmsrc/vendor/pocketmine/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#100210)
  #16 pmsrc/src/network/mcpe/NetworkSession(398): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#100217)
  #17 pmsrc/src/network/mcpe/NetworkSession(361): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#100210, string[4] ....)
  #18 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7] c.`a`..)
  #19 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[16] ...[.5..,..P<.L.)
  #20 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#99649)
  #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #22 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #23 pmsrc/src/Server(1661): pocketmine\snooze\SleeperHandler->sleepUntil(double 1652027571.841)
  #24 pmsrc/src/Server(1047): pocketmine\Server->tickProcessor()
  #25 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #26 pmsrc/src/PocketMine(327): pocketmine\server()
  #27 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by DavidGlitch04** [comment]
please edit the config of epiccustomalerts

**Comment by 0xliam627** [comment]
Dear @SiahRBLX,
> Your problem has been fixed, please download the release [here](https://github.com/David-pm-pl/EpicCustomAlerts/releases/tag/v0.0.1)
