### ISSUE TITLE
Death server crash bug

### ISSUE THREAD

**Issue by h20plex** [Taylor-pm-pl/EpicCustomAlerts#3]
Basically the plugin works joining the server but everytime a player dies the server crashes

**Comment by 0xliam627** [comment]
Please provide full error information!

**Comment by h20plex** [comment]
Here you go i put the errors on a paste bin 

https://pastebin.com/4GEXXTkH

**Comment by 0xliam627** [comment]
Fixed by 789cb41bb2c4fbc91ff79e213e6fbdf292fc612c
