### ISSUE TITLE
Fix server crash on startup

### ISSUE THREAD

**Issue by ClydeNoIQ** [Taylor-pm-pl/EpicCustomAlerts#4]
I did not manage to provide the error but hoping this issue to be fixed soon.

**Comment by 0xliam627** [comment]
Pls give crashdumps

**Comment by ClydeNoIQ** [comment]
![az_recorder_20230626_115920_edited](https://github.com/Taylor-pm-pl/EpicCustomAlerts/assets/86055764/dc90c2d6-b6c4-4b89-9387-6d389f8731f7)

**Comment by 0xliam627** [comment]
Fixed
